//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class activity_okgirl_profile
    {
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime birthday { get; set; }
        public string target_city { get; set; }
        public string id_card { get; set; }
        public int height { get; set; }
        public int weight { get; set; }
        public string native_place { get; set; }
        public string school { get; set; }
        public string profession { get; set; }
        public string telphone { get; set; }
        public string email { get; set; }
        public string img1 { get; set; }
        public string img2 { get; set; }
        public string experience { get; set; }
        public string intro { get; set; }
        public long userid { get; set; }
        public bool is_loliuser { get; set; }
        public System.DateTime apply_datetime { get; set; }
    }
}
