//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public long id { get; set; }
        public int cate_id { get; set; }
        public string title { get; set; }
        public string orig { get; set; }
        public string img { get; set; }
        public string bigimg { get; set; }
        public string url { get; set; }
        public string abst { get; set; }
        public string info { get; set; }
        public System.DateTime add_time { get; set; }
        public short ordid { get; set; }
        public bool is_hot { get; set; }
        public bool is_best { get; set; }
        public bool status { get; set; }
        public string seo_title { get; set; }
        public string seo_keys { get; set; }
        public string seo_desc { get; set; }
    }
}
