//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class box_products
    {
        public int id { get; set; }
        public int boxid { get; set; }
        public int pid { get; set; }
        public byte pquantity { get; set; }
        public int ptotal { get; set; }
        public int saletotal { get; set; }
        public byte maxquantitytype { get; set; }
        public bool iscommend { get; set; }
        public bool ishidden { get; set; }
        public short sortnum { get; set; }
        public int settotal { get; set; }
        public decimal discount { get; set; }
    }
}
