//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public int cid { get; set; }
        public string cname { get; set; }
        public int pcid { get; set; }
        public string cpath { get; set; }
        public byte ctype { get; set; }
        public int sortid { get; set; }
        public sbyte cstatu { get; set; }
        public string imgurl { get; set; }
        public string description { get; set; }
    }
}
