//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class coupon
    {
        public int id { get; set; }
        public string code { get; set; }
        public System.DateTime starttime { get; set; }
        public System.DateTime endtime { get; set; }
        public bool status { get; set; }
        public float price { get; set; }
        public System.DateTime addtime { get; set; }
        public Nullable<long> ordernmb { get; set; }
        public int rndnmb { get; set; }
        public int adminid { get; set; }
        public int owner_uid { get; set; }
        public string remark { get; set; }
    }
}
