//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class edm_stat_ymd
    {
        public long id { get; set; }
        public int eid { get; set; }
        public long pv { get; set; }
        public long uv { get; set; }
        public long hits { get; set; }
        public long unique_hits { get; set; }
        public System.DateTime etime { get; set; }
    }
}
