//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class edm_index
    {
        public short edm_no { get; set; }
        public string name { get; set; }
        public string tourl { get; set; }
        public int pv { get; set; }
        public int uv { get; set; }
        public int click { get; set; }
        public int unique_click { get; set; }
        public decimal click_rate { get; set; }
        public decimal unique_click_rate { get; set; }
        public System.DateTime c_datetime { get; set; }
    }
}
