//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class fee_product
    {
        public int id { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
        public int type { get; set; }
        public string pic { get; set; }
        public Nullable<int> score { get; set; }
        public string description { get; set; }
    }
}
