//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class giftcard
    {
        public string card_id { get; set; }
        public string card_pwd { get; set; }
        public short price { get; set; }
        public System.DateTime indate { get; set; }
        public int userid { get; set; }
        public System.DateTime activate_datetime { get; set; }
        public string remark { get; set; }
        public System.DateTime add_datetime { get; set; }
    }
}
