//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_stat
    {
        public long id { get; set; }
        public long itemid { get; set; }
        public string message { get; set; }
        public string @operator { get; set; }
        public int quantity { get; set; }
        public int add_time { get; set; }
        public bool status { get; set; }
        public int in_out_id { get; set; }
    }
}
