//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class inventory_item
    {
        public int id { get; set; }
        public string name { get; set; }
        public string intro { get; set; }
        public int firstcid { get; set; }
        public int secondcid { get; set; }
        public string relation_type { get; set; }
        public int relation_id { get; set; }
        public int relation_out_quantity { get; set; }
        public int inventory_in { get; set; }
        public int inventory_out { get; set; }
        public int inventory_real { get; set; }
        public int inventory_estimated { get; set; }
        public bool status { get; set; }
        public decimal price { get; set; }
        public int brandid { get; set; }
        public string category { get; set; }
        public string norms { get; set; }
        public System.DateTime validdate { get; set; }
        public string shelfinfo { get; set; }
        public decimal weight { get; set; }
        public string remark { get; set; }
        public bool exchange_interval { get; set; }
    }
}
