//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class member_order
    {
        public long ordernmb { get; set; }
        public string pay_bank { get; set; }
        public sbyte m_type { get; set; }
        public int price { get; set; }
        public int userid { get; set; }
        public System.DateTime addtime { get; set; }
        public Nullable<System.DateTime> paytime { get; set; }
        public bool state { get; set; }
        public bool ifavalid { get; set; }
        public string trade_no { get; set; }
        public short fromid { get; set; }
        public string frominfo { get; set; }
    }
}
