//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class msg
    {
        public int id { get; set; }
        public int from_uid { get; set; }
        public int to_uid { get; set; }
        public bool from_status { get; set; }
        public bool to_status { get; set; }
        public int k { get; set; }
        public int dataid { get; set; }
        public int addtime { get; set; }
    }
}
