//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MySqlEntities : DbContext
    {
        public MySqlEntities()
            : base("name=MySqlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activity_benefit> activity_benefit { get; set; }
        public virtual DbSet<activity_okgirl_profile> activity_okgirl_profile { get; set; }
        public virtual DbSet<activity_spread> activity_spread { get; set; }
        public virtual DbSet<area> area { get; set; }
        public virtual DbSet<article> article { get; set; }
        public virtual DbSet<box> box { get; set; }
        public virtual DbSet<box_detail> box_detail { get; set; }
        public virtual DbSet<box_products> box_products { get; set; }
        public virtual DbSet<box_project> box_project { get; set; }
        public virtual DbSet<box_project_list> box_project_list { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<coupon> coupon { get; set; }
        public virtual DbSet<edm_index> edm_index { get; set; }
        public virtual DbSet<edm_stat> edm_stat { get; set; }
        public virtual DbSet<edm_stat_ymd> edm_stat_ymd { get; set; }
        public virtual DbSet<fee_product> fee_product { get; set; }
        public virtual DbSet<filterword> filterword { get; set; }
        public virtual DbSet<follow> follow { get; set; }
        public virtual DbSet<inventory_in> inventory_in { get; set; }
        public virtual DbSet<inventory_item> inventory_item { get; set; }
        public virtual DbSet<inventory_out> inventory_out { get; set; }
        public virtual DbSet<inventory_stat> inventory_stat { get; set; }
        public virtual DbSet<inventory_virtual_relation> inventory_virtual_relation { get; set; }
        public virtual DbSet<jump_stat> jump_stat { get; set; }
        public virtual DbSet<member_order> member_order { get; set; }
        public virtual DbSet<msg> msg { get; set; }
        public virtual DbSet<msg_data> msg_data { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<products_brand> products_brand { get; set; }
        public virtual DbSet<products_buy_channel> products_buy_channel { get; set; }
        public virtual DbSet<products_evaluate> products_evaluate { get; set; }
        public virtual DbSet<products_evaluate_img> products_evaluate_img { get; set; }
        public virtual DbSet<products_evaluate_reply> products_evaluate_reply { get; set; }
        public virtual DbSet<products_evaluate_stat> products_evaluate_stat { get; set; }
        public virtual DbSet<products_package> products_package { get; set; }
        public virtual DbSet<products_pic> products_pic { get; set; }
        public virtual DbSet<products_stat> products_stat { get; set; }
        public virtual DbSet<products_tryout_info> products_tryout_info { get; set; }
        public virtual DbSet<send_log> send_log { get; set; }
        public virtual DbSet<send_task> send_task { get; set; }
        public virtual DbSet<share_task> share_task { get; set; }
        public virtual DbSet<shop> shop { get; set; }
        public virtual DbSet<shop_info> shop_info { get; set; }
        public virtual DbSet<stat_user_order> stat_user_order { get; set; }
        public virtual DbSet<system_config> system_config { get; set; }
        public virtual DbSet<tag_index> tag_index { get; set; }
        public virtual DbSet<tag_relation> tag_relation { get; set; }
        public virtual DbSet<task> task { get; set; }
        public virtual DbSet<task_child> task_child { get; set; }
        public virtual DbSet<task_order_stat> task_order_stat { get; set; }
        public virtual DbSet<telphone> telphone { get; set; }
        public virtual DbSet<think_admin> think_admin { get; set; }
        public virtual DbSet<think_group> think_group { get; set; }
        public virtual DbSet<think_node> think_node { get; set; }
        public virtual DbSet<think_role> think_role { get; set; }
        public virtual DbSet<think_simplelog> think_simplelog { get; set; }
        public virtual DbSet<user_activity> user_activity { get; set; }
        public virtual DbSet<user_address> user_address { get; set; }
        public virtual DbSet<user_atme> user_atme { get; set; }
        public virtual DbSet<user_behaviour_relation> user_behaviour_relation { get; set; }
        public virtual DbSet<user_behaviour_trace> user_behaviour_trace { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<users_invite> users_invite { get; set; }
        public virtual DbSet<activity_okgirl_surveystat> activity_okgirl_surveystat { get; set; }
        public virtual DbSet<activity_okgirl_votestat> activity_okgirl_votestat { get; set; }
        public virtual DbSet<api_access_log> api_access_log { get; set; }
        public virtual DbSet<box_order_set> box_order_set { get; set; }
        public virtual DbSet<box_products_cname> box_products_cname { get; set; }
        public virtual DbSet<box_project_relation> box_project_relation { get; set; }
        public virtual DbSet<club_benefit_flawless> club_benefit_flawless { get; set; }
        public virtual DbSet<club_benefit_votestat> club_benefit_votestat { get; set; }
        public virtual DbSet<club_prize> club_prize { get; set; }
        public virtual DbSet<club_users> club_users { get; set; }
        public virtual DbSet<email_blacklist> email_blacklist { get; set; }
        public virtual DbSet<giftcard> giftcard { get; set; }
        public virtual DbSet<ip_blacklist> ip_blacklist { get; set; }
        public virtual DbSet<member> member { get; set; }
        public virtual DbSet<product_effect_relation> product_effect_relation { get; set; }
        public virtual DbSet<products_survey> products_survey { get; set; }
        public virtual DbSet<products_survey_answer> products_survey_answer { get; set; }
        public virtual DbSet<products_survey_stat> products_survey_stat { get; set; }
        public virtual DbSet<promotion> promotion { get; set; }
        public virtual DbSet<task_stat> task_stat { get; set; }
        public virtual DbSet<think_access> think_access { get; set; }
        public virtual DbSet<tryout_stat> tryout_stat { get; set; }
        public virtual DbSet<url_click> url_click { get; set; }
    }
}
