//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_survey_stat
    {
        public int pid { get; set; }
        public sbyte surveyid { get; set; }
        public sbyte questionid { get; set; }
        public string answer { get; set; }
        public int userid { get; set; }
    }
}
