//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_evaluate
    {
        public int evaluateid { get; set; }
        public int productid { get; set; }
        public int userid { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string buychannel { get; set; }
        public bool skin_type { get; set; }
        public Nullable<System.DateTime> postdate { get; set; }
        public Nullable<int> agreenum { get; set; }
        public Nullable<int> replynum { get; set; }
        public Nullable<bool> contentlevel { get; set; }
        public int toptime { get; set; }
        public decimal score_avg { get; set; }
        public bool if_sync_weibo { get; set; }
    }
}
