//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public long pid { get; set; }
        public string pname { get; set; }
        public string product_alias { get; set; }
        public string productlist { get; set; }
        public int firstcid { get; set; }
        public int secondcid { get; set; }
        public int effectcid { get; set; }
        public int brandcid { get; set; }
        public string pimg { get; set; }
        public string goodssize { get; set; }
        public float goodsprice { get; set; }
        public string trialsize { get; set; }
        public float trialprice { get; set; }
        public string pintro { get; set; }
        public string taglist { get; set; }
        public string maincomponent { get; set; }
        public string officialweburl { get; set; }
        public string buyurl { get; set; }
        public int inventory { get; set; }
        public int inventoryreduced { get; set; }
        public long usednum { get; set; }
        public long thinkusenum { get; set; }
        public long evaluateusernum { get; set; }
        public long evaluatenum { get; set; }
        public int sharenum { get; set; }
        public int evaluate_lasttime { get; set; }
        public float totalscore { get; set; }
        public short surveyid { get; set; }
        public int fans_num { get; set; }
        public bool status { get; set; }
        public string readme { get; set; }
        public bool if_super { get; set; }
        public string sharelist { get; set; }
        public string ad_pic { get; set; }
        public string ad_url { get; set; }
        public string sale_tag { get; set; }
        public bool commend_tag { get; set; }
        public string try_viewpoint { get; set; }
        public string for_skin { get; set; }
        public string for_people { get; set; }
        public string for_hair { get; set; }
        public int sort_num { get; set; }
    }
}
