//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_brand
    {
        public int id { get; set; }
        public string name { get; set; }
        public string name_foreign { get; set; }
        public string firstchar { get; set; }
        public string foreign_firstchar { get; set; }
        public bool area { get; set; }
        public string founders { get; set; }
        public string found_time { get; set; }
        public string logo_url { get; set; }
        public string pic_url { get; set; }
        public string description { get; set; }
        public string website_url { get; set; }
        public int category_id_rel { get; set; }
        public int space_id_rel { get; set; }
        public string product_list { get; set; }
        public long visit_num { get; set; }
        public string visitor_list { get; set; }
        public int product_num { get; set; }
        public int tryout_num { get; set; }
        public int fans_num { get; set; }
        public int share_num { get; set; }
        public bool status { get; set; }
        public bool iscommend { get; set; }
        public bool if_super { get; set; }
        public string weibo_account { get; set; }
        public string grade { get; set; }
    }
}
