//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_buy_channel
    {
        public int id { get; set; }
        public long pid { get; set; }
        public string channelname { get; set; }
        public string url { get; set; }
        public int basehit { get; set; }
        public int realhit { get; set; }
        public int sortnum { get; set; }
        public System.DateTime addtime { get; set; }
        public decimal price { get; set; }
    }
}
