//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_stat
    {
        public long statid { get; set; }
        public string stattype { get; set; }
        public Nullable<long> productid { get; set; }
        public Nullable<long> userid { get; set; }
        public Nullable<decimal> score { get; set; }
        public Nullable<System.DateTime> postdate { get; set; }
        public Nullable<int> paramid { get; set; }
    }
}
