//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class products_evaluate_stat
    {
        public int id { get; set; }
        public System.DateTime stat_date { get; set; }
        public Nullable<int> inner_post_num { get; set; }
        public Nullable<int> real_post_num { get; set; }
        public Nullable<int> real_user_num { get; set; }
        public Nullable<int> reply_num { get; set; }
        public Nullable<int> reply_user_num { get; set; }
        public Nullable<int> post_total { get; set; }
        public Nullable<int> user_total { get; set; }
    }
}
