//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class promotion
    {
        public int code { get; set; }
        public string name { get; set; }
        public sbyte validate { get; set; }
        public string @params { get; set; }
        public string apikey { get; set; }
        public string pushurl { get; set; }
        public string remark { get; set; }
    }
}
