//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop_info
    {
        public int id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public int shopid { get; set; }
        public short sortid { get; set; }
        public bool status { get; set; }
        public System.DateTime c_datetime { get; set; }
    }
}
