//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_order_stat
    {
        public int userid { get; set; }
        public int shareid { get; set; }
        public long orderid { get; set; }
        public bool status { get; set; }
        public int addtime { get; set; }
    }
}
