//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class task_child
    {
        public int id { get; set; }
        public int relationid { get; set; }
        public int taskid { get; set; }
        public string title { get; set; }
        public int from { get; set; }
        public int to { get; set; }
        public string rules { get; set; }
        public short credit { get; set; }
        public sbyte status { get; set; }
    }
}
