//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class think_admin
    {
        public int id { get; set; }
        public string account { get; set; }
        public string nickname { get; set; }
        public string password { get; set; }
        public string bind_account { get; set; }
        public Nullable<long> last_login_time { get; set; }
        public string last_login_ip { get; set; }
        public Nullable<int> login_count { get; set; }
        public string verify { get; set; }
        public string email { get; set; }
        public string remark { get; set; }
        public long create_time { get; set; }
        public long update_time { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<byte> type_id { get; set; }
        public string info { get; set; }
    }
}
