//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class think_access
    {
        public int role_id { get; set; }
        public int node_id { get; set; }
        public bool level { get; set; }
        public short pid { get; set; }
        public string module { get; set; }
    }
}
