//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class think_node
    {
        public int id { get; set; }
        public string name { get; set; }
        public string title { get; set; }
        public Nullable<bool> status { get; set; }
        public string remark { get; set; }
        public Nullable<int> sort { get; set; }
        public int pid { get; set; }
        public bool level { get; set; }
        public bool type { get; set; }
        public Nullable<byte> group_id { get; set; }
    }
}
