//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class think_role
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<short> pid { get; set; }
        public Nullable<bool> status { get; set; }
        public string remark { get; set; }
        public string ename { get; set; }
        public long create_time { get; set; }
        public long update_time { get; set; }
    }
}
