//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_activity
    {
        public int id { get; set; }
        public int userid { get; set; }
        public string activitytype { get; set; }
        public string gifttype { get; set; }
        public string giftinfo { get; set; }
        public System.DateTime addtime { get; set; }
        public string remark { get; set; }
    }
}
