//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_atme
    {
        public int id { get; set; }
        public int relationid { get; set; }
        public bool relationtype { get; set; }
        public int sourceid { get; set; }
        public bool sourcetype { get; set; }
        public bool state { get; set; }
        public long level { get; set; }
        public bool pk { get; set; }
        public int hot { get; set; }
        public int addtime { get; set; }
    }
}
