//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_address
    {
        public int id { get; set; }
        public int userid { get; set; }
        public string linkman { get; set; }
        public string telphone { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string district { get; set; }
        public string address { get; set; }
        public string postcode { get; set; }
        public bool if_active { get; set; }
        public System.DateTime addtime { get; set; }
        public int if_del { get; set; }
    }
}
