//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class users_invite
    {
        public int id { get; set; }
        public int code { get; set; }
        public Nullable<bool> status { get; set; }
        public string remark { get; set; }
        public long owner_uid { get; set; }
        public int adminid { get; set; }
        public System.DateTime addtime { get; set; }
    }
}
