//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LW.EFEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public long userid { get; set; }
        public string nickname { get; set; }
        public string password { get; set; }
        public string usermail { get; set; }
        public bool state { get; set; }
        public System.DateTime addtime { get; set; }
        public int score { get; set; }
        public int experience { get; set; }
        public string invitecode { get; set; }
        public int invite_uid { get; set; }
        public short order_num { get; set; }
        public short evaluate_num { get; set; }
        public short collect_num { get; set; }
        public short follow_num { get; set; }
        public short fans_num { get; set; }
        public short blog_num { get; set; }
        public short coupon_num { get; set; }
        public bool if_super { get; set; }
        public bool is_mobile { get; set; }
        public bool tel_status { get; set; }
        public bool is_solution { get; set; }
        public bool is_spreader { get; set; }
        public string know_way { get; set; }
    }
}
